name: Build
# Put your personal access token in a repository secret named PAT for cross-repository access
on:
  workflow_dispatch:

env:
  PROJECT_NAME: "[Dekken] Neir_Sage"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.6.0
        with:
          submodules: recursive

      #- name: Setup Powershell Script
      #  run: .\setup.ps1 -Part 0
      - name: Run Powershell Script
        run: .\setup.ps1
      #  run: .\run.ps1 -Name "NierSage\-" -OutputName "`[Dekken`] Neir_Sage" -Version "1.0.0" -Website "" -Tags @() -Description ""
      #- name: End Powershell Script
      #  run: .\setup.ps1 -Part 1

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ${{env.PROJECT_NAME}}
          path: "${{env.PROJECT_NAME}}.pmp"
          if-no-files-found: error

  release:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.6.0
        with:
          fetch-depth: 0

      - name: Download artifact
        uses: actions/download-artifact@v4.1.7
        id: download
        with:
          name: "${{env.PROJECT_NAME}}"

      - name: Create release
        uses: softprops/action-gh-release@v0.1.15
        with:
          name: ${{ env.PROJECT_NAME }} ${{steps.version.outputs.prop}}
          tag_name: "_temp"
          body: ${{ github.events.commits[0].message }}
          files: ${{ steps.download.outputs.download-path }}\latest.zip

      - name: Trigger plugin repo update
        uses: peter-evans/repository-dispatch@v2.1.1
        with:
          token: ${{ secrets.PAT }}
          repository: ${{env.PLUGIN_REPO}}
          event-type: new-release
